defaults:
  - models/backbones: mae
  - _self_

loglevel: INFO
mlflow_uri: "sqlite:///mlflow.db"
mlflow_log_system_metrics: true
eval_only_mode: true

datamodule: 
  _target_: datasets.simulated_dataset.HologramDataModule
  data_dir: "C:/Users/kelle/Documents/storage/xray/Raw_holo_sim/reduced2"
  mode: "rgb"
  total_samples: 5000
  train_fraction: 1.0

experiments:
  batch_size: 2