defaults:
  - models/baselines: resnet_50
  - override hydra/sweeper: optuna

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 42
    direction: minimize
    study_name: Baseline Hyperparameter Optimization
    storage: "sqlite:///optuna.db"
    n_trials: 20
    n_jobs: 1
    params:
      models.baselines.model.lr: interval(1e-5, 5e-4)

loglevel: INFO
mlflow_uri: "sqlite:///mlflow.db"
mlflow_log_system_metrics: true
data_dir: "C:\\Users\\kelle\\Documents\\storage\\xray\\Raw_Holo"
batch_size: 1
hyperparameter_optimization_mode: false