defaults:
  - models/baselines: unet # or resnet_18
  - _self_

loglevel: INFO
mlflow_uri: "sqlite:///mlflow.db"
mlflow_log_system_metrics: true
batch_size: 512

datamodule: 
  _target_: datasets.simulated_dataset.HologramDataModule
  data_dir: "PATH_TO_YOUR_DATASET_SHARDS_DIRECTORY"
  mode: "raw" # or "diff" for resnet_18 baseline
  total_samples: 250000
  train_fraction: 1.0