loglevel: INFO
mlflow_uri: "http://localhost:5000/"
mlflow_log_system_metrics: true

experiment:
  batch_size: 4
  data_dir: "C:\\Users\\kelle\\Documents\\storage\\xray\\Raw_Holo"
  variations:
      - name: "Random MAE Experiment"
        checkpoint_dir: "C:\\Users\\kelle\\Documents\\storage\\xray\\checkpoints\\random_mae"
        parameters:
          model:
            patch_size: 32
            embed_dim: 768
            mask_ratio: 0.75
            lr: 1.5e-4
          weight_decay: 0.05
          num_epochs: 100