model:
  checkpoint_path: "C:/Users/kelle/Documents/storage/xray/checkpoints/mae/2026-08-12_15-39-07/backbone-00-val_loss=0.0018.ckpt"
  encoder: 
    _target_: models.lightning_modules.backbones.mae.LitMAE
    pretext_strategy: None
    img_size: 224
  use_pretrained_dino: false
  channels: 3
  name: "TSNE Feature Evaluation"

loglevel: INFO
mlflow_uri: "sqlite:///mlflow.db"
mlflow_log_system_metrics: true
batch_size: 4

datamodule: 
  _target_: datasets.simulated_dataset.HologramDataModule
  data_dir: "C:/Users/kelle/Documents/storage/xray/Raw_holo_sim/reduced2"
  mode: "rgb"
  total_samples: 5000