name: "ResNet-18 Classification Baseline"
checkpoint_dir: "C:/Users/kelle/Documents/storage/xray/checkpoints/baselines/resnet/${oc.env:SLURM_JOB_ID, ${now:%Y-%m-%d_%H-%M-%S}}"
visualization_type: "multi_label_classification"
log_every_n_epochs: 1

model:
  _target_: models.baselines.resnet18_baseline.LitResnetBaseline
  num_classes: 2
  lr: 0.001
  weight_decay: 0.05
  pretrained: false
  channels: 1

trainer:
  max_epochs: 2
  monitor_metric: "val/f1_micro"
  monitor_mode: "max"