name: "ResNet-18 Classification Baseline"
checkpoint_dir: "C:\\Users\\kelle\\Documents\\storage\\xray\\checkpoints\\baselines\\resnet"
visualization_type: "multi_label_classification"

model:
  _target_: models.baselines.resnet50_baseline.LitResnetBaseline
  num_classes: 3
  lr: 0.001
  pretrained: false

trainer:
  max_epochs: 1
  monitor_metric: "val/f1_micro"
  monitor_mode: "max"