name: "Unet Segmentation Baseline"
checkpoint_dir: "C:\\Users\\kelle\\Documents\\storage\\xray\\checkpoints\\baselines\\unet"
visualization_type: "segmentation"

model:
  _target_: models.baselines.unet_baseline.LitUnetBaseline
  lr: 0.001
  weight_decay: 0.01
  encoder_name: "tu-convnext_base.dinov3_lvd1689m"  # tu-convnext_base.dinov3_lvd1689m

trainer:
  max_epochs: 1
  monitor_metric: "val/loss"
  monitor_mode: "min"