name: "Unet Segmentation Baseline"
checkpoint_dir: "PATH_TO_YOUR_CHECKPOINT_DIRECTORY/baselines/unet/${oc.env:SLURM_JOB_ID, ${now:%Y-%m-%d_%H-%M-%S}}"
visualization_type: "segmentation"
log_every_n_epochs: 20

model:
  _target_: models.baselines.unet_baseline.LitUnetBaseline
  lr: 0.0001
  weight_decay: 0.01
  warmup_ratio: 0.1
  encoder_name: "resnet18"
  channels: 1

trainer:
  max_epochs: 500
  monitor_metric: "val/F2_Score"
  monitor_mode: "max"