name: "LitSimMIM Experiment"
checkpoint_dir: "C:\\Users\\kelle\\Documents\\storage\\xray\\checkpoints\\random_mae"
parameters:
  model:
    _target_: models.lightning_modules.backbones.sim_mim.LitSimMIM
    pretext_strategy:
      _target_: models.lightning_modules.pretext_tasks.random_real_space_masking.RandomMaskingRealSpaceStrategy
      img_size: 960
      patch_size: 16
      mask_ratio: 0.75
    patch_size: 16
    embed_dim: 768
    mask_ratio: 0.75
    lr: 1.5e-4
    warmup_ratio: 0.1
    weight_decay: 0.05
  num_epochs: 1