name: "Multi-Label Classification"
checkpoint_dir: "C:\\Users\\kelle\\Documents\\storage\\xray\\checkpoints\\mae\\classification"
visualization_type: "multi_label_classification"

backbone:
  module_class: "models.lightning_modules.backbones.mae.LitMAE" 
  checkpoint_path: "C:\\Users\\kelle\\Documents\\storage\\xray\\checkpoints\\mae\\mae-epoch=49-train_loss=0.0000.ckpt"

task:
  _target_: models.lightning_modules.tasks.classification_task.LitClassificationTask
  num_classes: 3 
  freeze_encoder: true
  lr: 1e-4
  warmup_ratio: 0.1
  weight_decay: 0.05
  
  head:
    _target_: models.heads.classification_head.ViTMultiLabelClassificationHead
    embed_dim: 768
    hidden_dim: 256
    num_classes: 3

trainer:
  max_epochs: 1
  monitor_metric: "val/f1_micro"
  monitor_mode: "max"