name: "Multi-Label Classification"
checkpoint_dir: "PATH_TO_YOUR_CHECKPOINT_DIRECTORY/mae/classification/${oc.env:SLURM_JOB_ID, ${now:%Y-%m-%d_%H-%M-%S}}"
visualization_type: "multi_class_classification"
checkpoint_path: "PATH_TO_TRAINED_SEGMENTATION_MODEL" # for evaluation only mode

backbone:
  module_class: "models.lightning_modules.backbones.mae.LitMAE"
  checkpoint_path: "PATH_TO_YOUR_TRAINED_BACKBONE_MODEL"
  use_pretrained_dino: false
  channels: 3

task:
  _target_: models.lightning_modules.tasks.classification_task.LitClassificationTask
  num_classes: 3
  freeze_encoder: false
  lr: 1e-4
  encoder_lr: 1e-5
  warmup_ratio: 0.1
  weight_decay: 0.05
  
  head:
    _target_: models.heads.classification_head.ViTMultiLabelClassificationHead
    embed_dim: 768
    hidden_dim: 256
    num_classes: 3

trainer:
  max_epochs: 200
  monitor_metric: "val/f1_macro"
  monitor_mode: "max"