name: "Segmentation"
checkpoint_dir: "C:/Users/kelle/Documents/storage/xray/checkpoints/random_mae/segmentation/${oc.env:SLURM_JOB_ID, ${now:%Y-%m-%d_%H-%M-%S}}"
visualization_type: "segmentation"
log_every_n_epochs: 1

backbone:
  module_class: "models.lightning_modules.backbones.mae.LitMAE"
  checkpoint_path: "C:/Users/kelle/Documents/storage/xray/checkpoints/mae/<INSERT FOLDER/>/backbone-epoch=01-train_loss=0.0000.ckpt"

task:
  _target_: models.lightning_modules.tasks.segmentation_task.LitSegmentationTask
  freeze_encoder: true
  lr: 1e-4
  encoder_lr: 1e-5
  warmup_ratio: 0.1
  weight_decay: 0.05
  
  head:
    _target_: models.heads.segmentation_head.ViTSegmentationHead
    embed_dim: 768
    num_classes: 1
    patch_size: 8
    img_size: 224

trainer:
  max_epochs: 50
  monitor_metric: "val/F2_Score"
  monitor_mode: "max"