name: "Segmentation"
checkpoint_dir: "PATH_TO_YOUR_CHECKPOINT_DIRECTORY/mae/segmentation/${oc.env:SLURM_JOB_ID, ${now:%Y-%m-%d_%H-%M-%S}}"
visualization_type: "segmentation"
log_every_n_epochs: 20
checkpoint_path: "PATH_TO_TRAINED_SEGMENTATION_MODEL" # for evaluation only mode

backbone:
  module_class: "models.lightning_modules.backbones.mae.LitMAE"
  checkpoint_path: "PATH_TO_YOUR_TRAINED_BACKBONE_MODEL"
  use_pretrained_dino: false
  channels: 3

task:
  _target_: models.lightning_modules.tasks.segmentation_task.LitSegmentationTask
  selected_loss: "dice"
  freeze_encoder: false
  lr: 1e-4
  encoder_lr: 1e-5
  warmup_ratio: 0.1
  weight_decay: 0.05
  
  head:
    _target_: models.heads.segmentation_dpt_head.DPTSegmentationHead
    encoder_name: "tu-vit_base_patch16_224"

trainer:
  max_epochs: 200
  monitor_metric: "val/F2_Score"
  monitor_mode: "max"